--Landing to Flattened

--CLIENT 
INSERT INTO HAKKODA.FLATTENED.CLIENT
SELECT CLIENT_ID, CLIENT_NAME, CLIENT_LASTNAME, EMAIL
FROM HAKKODA.LANDING.TRANSACTIONS;

--ADDRESS
INSERT INTO HAKKODA.FLATTENED.ADDRESS
SELECT ADDRESS_ID,STREET,CITY,STATE,ZIP_CODE
FROM HAKKODA.LANDING.TRANSACTIONS;

--STORE
INSERT INTO HAKKODA.FLATTENED.STORE
SELECT STORE_ID,STORE_NAME,LOCATION
FROM HAKKODA.LANDING.TRANSACTIONS;

--PRODUCT
INSERT INTO HAKKODA.FLATTENED.PRODUCT
SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY,BRAND
FROM HAKKODA.LANDING.TRANSACTIONS;